# Generated by Django 5.2 on 2025-04-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.TextField(default='Rahim'),
        ),
    ]
